### ISSUE TITLE
Change difficulty option is missing if I use a Vita converted save.

### ISSUE THREAD

**Issue by Kristof910** [cfxxldev/P4GPC_Savegame_Helper#2]
So in the PC version you can customize the difficulty on your first playthrough, but this option is missing for me from the System menu if I load up a Vita save. All of my Vita saves don't have this option but if I make a new PC save file I have it, screenshot below!
![Annotation 2020-06-17 193029](https://user-images.githubusercontent.com/57455895/85025993-c9ee7680-b180-11ea-8eca-b6d359b953d1.png)

**Comment by cfxxldev** [comment]
I'm marking this as a possible enhancement. But I don't think this should be added to any of the 2 existing tools but rather be put into a new tool.

**Comment by Kristof910** [comment]
> I'm marking this as a possible enhancement. But I don't think this should be added to any of the 2 existing tools but rather be put into a new tool.

Thank you for your response!

**Comment by cfxxldev** [comment]
But please don't hold your breath for this. I haven't been able to find out what location of in the savefile needs to be changed.

**Comment by Kristof910** [comment]
> But please don't hold your breath for this. I haven't been able to find out what location of in the savefile needs to be changed.

It's okay, thanks for trying! I don't know anything about these stuff but my guess would be to find out what difference a PC save file have compared to a Vita, probably there are some check marks what specifically tells the game that it can enable difficulty switch on the first run if it was created on the PC, but I don't know anything what can help you! :/

**Comment by cfxxldev** [comment]
both savegames would have to be otherwise identical (at least mostly). The best would be to have 2 savegames both at the very first savepoint the game gives you, one started on vita and one started on pc. I don't have such a vita save so if someone can provide one i could try to look into it.

**Comment by Kristof910** [comment]
> both savegames would have to be otherwise identical (at least mostly). The best would be to have 2 savegames both at the very first savepoint the game gives you, one started on vita and one started on pc. I don't have such a vita save so if someone can provide one i could try to look into it.

I made 2 new save files on my Vita and on PC with identical difficulty levels and player names, I saved it after Dojima parked his car at the gas station, here is the link: https://www.mediafire.com/file/l5lqmsatx8cpapu/P4G.rar/file

**Comment by cfxxldev** [comment]
I'll look into it next weekend.

**Comment by cfxxldev** [comment]
@Kristof910 
The latest PreRelease build has an additional tool: P4GPC_DifficultyMenu_Enabler.exe.
https://github.com/cfxxldev/P4GPC_Savegame_Helper/releases/tag/latest

You use it like the other tools: Drag and drop your safefile onto the exe and the tool does the work.

**Comment by Kristof910** [comment]
> @Kristof910
> The latest PreRelease build has an additional tool: P4GPC_DifficultyMenu_Enabler.exe.
> https://github.com/cfxxldev/P4GPC_Savegame_Helper/releases/tag/latest
> 
> You use it like the other tools: Drag and drop your safefile onto the exe and the tool does the work.

OMG dude you are a life saver, I didn't expected you to make it happened, I started my playthrough on Hard and I was struggling so bad, I didn't wanted to use any trainers but this will help me a lot, I really appreciate your time and dedication for me, thanks again !
