### ISSUE TITLE
Cannot change difficulty in a converted psvita save

### ISSUE THREAD

**Issue by HexRebuilt** [cfxxldev/P4GPC_Savegame_Helper#4]
Hi, i'm trying to use the P4GPC_DifficultyMenu_Enabler, but if i drag and drop the save file, nothing changes in the in-game menu and i cannot access the menu, even if i set in the binslot "Times Cleared:1".

![immagine](https://github.com/user-attachments/assets/59907bd4-605f-46d8-9e52-ace865052fa2)
after the terminal output, to close it i have to press 2 times enter and it closes.

those are the save files.
[save_file.zip](https://github.com/user-attachments/files/18135489/save_file.zip)

Shall I just create from scratch a new file and allign with this one with the save editor?

**Comment by HexRebuilt** [comment]
SOLVED.
i had to:
1. read your source code to understand where to look on my file
2. wonder a bit guessing why in my file there was a 0x04
![immagine](https://github.com/user-attachments/assets/27c371dd-f36d-4aa8-8b9f-494a7072415f)
3.  set it back to 0
4. run your lifesaving script
5. change the difficulty to normal
6. beat the shit out of mitsuo

Thanks man for the script in the first place

**Comment by cfxxldev** [comment]
If I remember correctly (it's been a while since I had to think about P4G :)), the difficulty enabler only works on save-files, that had been loaded and then saved in the PC-version at least once.

**Comment by HexRebuilt** [comment]
Yes that was my case. The file was converted 20+h of game time before but for some reason it had a 4 instead of a 0 and the script was not doing anything. thankfully you had the source available. 
Thanks for the reverse engieering
